<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace TRS\AsyncNotification\models\base;

use Yii;

/**
 * This is the base-model class for table "push_device".
 *
 * @property integer $id
 * @property string $type
 * @property string $device_id
 * @property string $owner_id
 * @property string $created_at
 */
abstract class PushDevice extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'push_device';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [ [ 'type', 'device_id' ], 'required' ],
            [ [ 'created_at' ], 'safe' ],
            [ [ 'type', 'owner_id' ], 'string', 'max' => 255 ],
            [ [ 'device_id' ], 'string', 'max' => 255 ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'         => Yii::t('app', 'ID'),
            'type'       => Yii::t('app', 'Type'),
            'device_id'  => Yii::t('app', 'Device ID'),
            'owner_id'   => Yii::t('app', 'Owner ID'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }


}
