<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace TRS\AsyncNotification\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "sms_message".
 *
 * @property integer $id
 * @property string $body_text
 * @property string $status
 * @property integer $try_count
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \TRS\AsyncNotification\models\SmsRecipient[] $smsRecipients
 * @property string $aliasModel
 */
abstract class SmsMessage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%sms_message}}';
    }

    public static function modelName()
    {
        return 'SmsMessage';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['body_text', 'status', 'try_count'], 'required'],
            [['try_count'], 'integer'],
            [['body_text', 'status'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'body_text' => Yii::t('app', 'Body Text'),
            'status' => Yii::t('app', 'Status'),
            'try_count' => Yii::t('app', 'Try Count'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmsRecipients()
    {
        return $this->hasMany(\TRS\AsyncNotification\models\SmsRecipient::className(), ['message_id' => 'id']);
    }




}
