<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace TRS\AsyncNotification\models\base;

use Yii;

/**
 * This is the base-model class for table "sms_recipient".
 *
 * @property integer $id
 * @property integer $message_id
 * @property string $phone
 *
 * @property \TRS\AsyncNotification\models\SmsMessage $message
 * @property string $aliasModel
 */
abstract class SmsRecipient extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%sms_recipient}}';
    }

    public static function modelName()
    {
        return 'SmsRecipient';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message_id', 'phone'], 'required'],
            [['message_id'], 'integer'],
            [['phone'], 'string', 'max' => 255],
            [['message_id'], 'exist', 'skipOnError' => true, 'targetClass' => SmsMessage::className(), 'targetAttribute' => ['message_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app','ID'),
            'message_id' => Yii::t('app','Message ID'),
            'phone' => Yii::t('app','Phone'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessage()
    {
        return $this->hasOne(\TRS\AsyncNotification\models\SmsMessage::className(), ['id' => 'message_id']);
    }




}
